### ISSUE TITLE
Robots.txt not routing

### ISSUE THREAD

**Issue by fsmythe** [PxlSyl/tailwind-nextjs-starter-blog-i18n#36]
**Describe the bug**
Hi, thanks for the template, really really stuff. I've got everything working perfectly however the robots.txt doesn't seem accessible either by me or crawlers (google etc).

Error I get locally:
![image](https://github.com/user-attachments/assets/be5b7bd6-8f0a-4365-bc07-4579ad0f6f1a)
 
Error I get on live site:
![image](https://github.com/user-attachments/assets/c7318042-5470-4ad2-bd78-32cb79cab7f6)

The logs:
![image](https://github.com/user-attachments/assets/920e9fa4-455b-41e7-8c2b-0ff4c0e53131)

`TypeError: Cannot read properties of undefined (reading 'body')
    at g (/var/task/.next/server/app/[locale]/[authors]/page.js:1:15873)
    at eh (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134786)
    at e (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:137671)
    at ek (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:138145)
    at Array.toJSON (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135755)
    at stringify (<anonymous>)
    at eR (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142219)
    at eE (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142698)
    at Timeout._onTimeout (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135475)
    at listOnTimeout (node:internal/timers:581:17) {
  digest: '3283440806'
}`

**Expected behavior**
Expect to able to see the robots.txt and for indexers to crawl it

**Screenshots**

**Additional context**
Thanks!

**Comment by PxlSyl** [comment]
Hi! I'll prob need to update it all to Next 15 + etc. But if you find a solution for this, please make a PR and let me know!
